[tools]
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
selene = "kampfkarren/selene@0.27.1"
rojo = "rojo-rbx/rojo@7.4.4"
luau-lsp = "JohnnyMorganz/luau-lsp@1.35.0"
stylua = "JohnnyMorganz/StyLua@2.0.1"
pseudo-enum = "nightcycle/pseudo-enum@1.0.5"
darklua = "seaofvoices/darklua@0.14.0"
moonwave = "evaera/moonwave@1.1.3"
