[tools]
wally = { source = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.3.1" }
selene = { source = "kampfkarren/selene", version = "0.27.1" }
rojo = { source = "rojo-rbx/rojo", version = "7.4.1" }
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "1.29.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.20.0" }
wally-update = { source = "nightcycle/wally-update", version = "0.1.2" }
pseudo-enum = { source = "nightcycle/pseudo-enum", version = "0.2.2" }
