title = "Synthetic"  # From Git
gitRepoUrl = "https://github.com/nightcycle/synthetic.git" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""

# From git:
organizationName = "Nightcycle"
projectName = "Synthetic"
url = "https://nightcycle.github.io"
baseUrl = "/synthetic"
tagline = "Material UI inspired elements ported to Fusion!"

[navbar]
hideableSidebar = true

[footer]
style = "dark"
copyright = "Copyright © 2022 Nightcycle. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"
