build_path = "src/Enums.luau"
use_union_types_for_tree = false
use_union_types_for_export = true

[enums]
FontType = [
	"DisplayLarge",
	"DisplayMedium",
	"DisplaySmall",
	"HeadlineLarge",
	"HeadlineMedium",
	"HeadlineSmall",
	"TitleLarge",
	"TitleMedium",
	"TitleSmall",
	"BodyLarge",
	"BodyMedium",
	"BodySmall",
	"LabelLarge",
	"LabelMedium",
	"LabelSmall",
]
ButtonStateType = ["Enabled", "Disabled", "Hovered", "Focused", "Pressed"]
SchemeType = ["Light", "Dark"]
CustomColorType = [
	"Custom",
	"OnCustom",
	"CustomContainer",
	"OnCustomContainer"
]
SelectionState = [
	"Selected",
	"Unselected"
]
ColorRoleType = [
	"Primary",
	"OnPrimary",
	"PrimaryContainer",
	"OnPrimaryContainer",
	"Secondary",
	"OnSecondary",
	"SecondaryContainer",
	"OnSecondaryContainer",
	"Tertiary",
	"OnTertiary",
	"TertiaryContainer",
	"OnTertiaryContainer",
	"Error",
	"OnError",
	"ErrorContainer",
	"OnErrorContainer",
	"Background",
	"OnBackground",
	"Surface",
	"OnSurface",
	"SurfaceVariant",
	"OnSurfaceVariant",
	"Outline",
	"OutlineVariant",
	"Shadow",
	"Scrim",
	"InverseSurface",
	"InverseOnSurface",
	"InversePrimary",
	"SurfaceDim",
	"SurfaceBright",
	"SurfaceContainerLowest",
	"SurfaceContainerLow",
	"SurfaceContainer",
	"SurfaceContainerHigh",
	"SurfaceContainerHighest",
	"SurfaceTint",
]
PaletteType = [
	"Primary",
	"Secondary",
	"Tertiary",
	"Neutral",
	"NeutralVariant",
	"Error",
]
TransitionType = [
	"Emphasized",
	"EmphasizedDecelerate",
	"EmphasizedAccelerate",
	"Standard",
	"StandardDecelerate",
	"StandardAccelerate",
]
TransitionDuration = [
	"Short1",
	"Short2",
	"Short3",
	"Short4",
	"Medium1",
	"Medium2",
	"Medium3",
	"Medium4",
	"Long1",
	"Long2",
	"Long3",
	"Long4",
	"ExtraLong1",
	"ExtraLong2",
	"ExtraLong3",
	"ExtraLong4",
	
]