[package]
name = "nightcycle/synthetic"
description = "Material UI inspired elements made with Cold-Fusion"
version = "5.0.0"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
ColdFusion = "nightcycle/cold-fusion@9.0.7"
Signal = "nightcycle/signal@1.0.2"
Maid = "nightcycle/maid@1.1.4"
Format = "nightcycle/format@0.1.3"
MeshUtil = "nightcycle/mesh-util@1.0.3"
Fusion = "elttob/fusion@0.2.0"
Roact = "roblox/roact@1.4.0"
MaterialIcons = "nightcycle/material-icons@1.0.1"
CurveUtil = "nightcycle/curve-util@1.0.0"