[package]
name = "nightcycle/synthetic"
description = "Material UI inspired elements made with Cold-Fusion"
version = "4.0.21"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
coldfusion = "nightcycle/cold-fusion@^5.0.21"
signal = "nightcycle/signal@^1.0.2"
maid = "nightcycle/maid@^1.0.2"
format = "nightcycle/format@^0.1.3"
math = "nightcycle/luau-math@^1.3.1"
