[package]
name = "nightcycle/synthetic"
description = "Material UI inspired elements ported to Fusion!"
version = "2.4.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
fusion = "elttob/fusion@^0.1.1-beta"
maid = "quenty/maid@^2.0.1-canary"
signal = "quenty/signal@^2.0.0-canary"
filter = "nightcycle/filter@^1.0.2"
attributer = "nightcycle/attributer@2.0.0"
typography = "nightcycle/typography@^1.1.5"
viewport = "nightcycle/viewport-handler@1.0.0"
color-utils = "csqrl/colour-utils@1.1.1"
enumerator = "howmanysmall/enumerator@2.2.3"