[package]
name = "nightcycle/synthetic"
description = "Material UI inspired elements made with Cold-Fusion"
version = "3.4.2"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
coldfusion = "nightcycle/cold-fusion@^2.1.0"
isotope = "nightcycle/isotope@^1.3.1"
signal = "nightcycle/signal@^1.0.0"
maid = "nightcycle/maid@^1.0.2"
format = "nightcycle/format@0.1.2"
math = "nightcycle/luau-math@1.0.1"