[package]
name = "nightcycle/synthetic"
description = "Material UI inspired elements made with Cold-Fusion"
version = "5.0.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode", "media", "*.mp4", "*.gif", "*.png"]

[dependencies]
Maid = "nightcycle/maid@2.0.0"
MaterialIcons = "nightcycle/material-icons-default-dp18-1x@1.0.3"
OutlinedMaterialIcons = "nightcycle/material-icons-outlined-dp18-1x@1.0.3"
TableUtil = "nightcycle/table-util@2.0.0"
HashUtil = "boatbomber/hashlib@1.0.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
React = "jsdotlua/react@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"