[package]
name = "nightcycle/synthetic"
description = "Material UI inspired elements made with Cold-Fusion"
version = "3.0.6"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
iconlabel = "nightcycle/iconlabel@0.1.14"
textlabel = "nightcycle/textlabel@0.1.8"
checkbox = "nightcycle/checkbox@0.1.7"
radiobutton = "nightcycle/radio-button@0.1.8"
switch = "nightcycle/switch@0.1.7"

