[package]
name = "nightcycle/synthetic-react"
description = "Material UI inspired elements made in React"
version = "11.1.3"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode", "media", "*.mp4", "*.gif", "*.png"]

[dependencies]
Maid = "nightcycle/maid@2.2.1"
MaterialIcons = "nightcycle/material-icons-default-dp24-1x@1.0.3"
OutlinedMaterialIcons = "nightcycle/material-icons-outlined-dp24-1x@1.0.3"
TableUtil = "nightcycle/table-util@3.0.2"
HashUtil = "boatbomber/hashlib@1.0.0"
CurveUtil = "nightcycle/curve-util@1.0.0"
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
Spring = "nightcycle/spring@1.0.0"
