--!strict
--!native
-- Services
-- Packages
-- Modules
local Enums = require("@proj/Enums")
-- Types
-- Constants
-- Variables
-- References
-- Private Functions
-- Class
return {
	[Enums.TransitionDuration.Short1] = 50 / 1000,
	[Enums.TransitionDuration.Short2] = 100 / 1000,
	[Enums.TransitionDuration.Short3] = 150 / 1000,
	[Enums.TransitionDuration.Short4] = 200 / 1000,
	[Enums.TransitionDuration.Medium1] = 250 / 1000,
	[Enums.TransitionDuration.Medium2] = 300 / 1000,
	[Enums.TransitionDuration.Medium3] = 350 / 1000,
	[Enums.TransitionDuration.Medium4] = 400 / 1000,
	[Enums.TransitionDuration.Long1] = 450 / 1000,
	[Enums.TransitionDuration.Long2] = 500 / 1000,
	[Enums.TransitionDuration.Long3] = 550 / 1000,
	[Enums.TransitionDuration.Long4] = 600 / 1000,
	[Enums.TransitionDuration.ExtraLong1] = 700 / 1000,
	[Enums.TransitionDuration.ExtraLong2] = 800 / 1000,
	[Enums.TransitionDuration.ExtraLong3] = 900 / 1000,
	[Enums.TransitionDuration.ExtraLong4] = 1000 / 1000,
}
